version: '2'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./docker_db/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=tictactoe
      - MYSQL_USER=tictactoe
      - MYSQL_PASSWORD=tictactoe